networks:
  static-network:
    ipam:
      config:
        - subnet: 172.22.0.0/16
services:
  web:
    build: .
    ports:
      - "3099:3099"
    restart: unless-stopped
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    networks:
      static-network:
        ipv4_address: 172.22.0.2
    volumes:
      - .:/app
  db:
    image: postgres:17
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
