networks:
  static-network:
    ipam:
      config:
        - subnet: 172.22.0.0/16
services:
  web:
    build: .
    ports:
      - "3099:3099"
    restart: unless-stopped
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    networks:
      static-network:
        ipv4_address: 172.22.0.2
    volumes:
      - .:/app

